<?php
/**
 * AskPermissionSignInError
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BCFLEX API
 *
 * BCFLEX Public API Documentation
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AskPermissionSignInError Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AskPermissionSignInError
{
    /**
     * Possible values of this enum
     */
    const USER_ID_DECRYPTION_FALURE = 'UserIdDecryptionFalure';
    const NO_SUCH_USER_ID = 'NoSuchUserId';
    const NO_DEVICE_FOR_TWO_STEP = 'NoDeviceForTwoStep';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::USER_ID_DECRYPTION_FALURE,
            self::NO_SUCH_USER_ID,
            self::NO_DEVICE_FOR_TWO_STEP,
        ];
    }
}


