<?php
/**
 * DevicePermissionRequestType
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BCFLEX API
 *
 * BCFLEX Public API Documentation
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DevicePermissionRequestType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DevicePermissionRequestType
{
    /**
     * Possible values of this enum
     */
    const ENABLE_TWO_FACTOR = 'EnableTwoFactor';
    const CANCEL_ENABLE_TWO_FACTOR = 'CancelEnableTwoFactor';
    const DISABLE_TWO_FACTOR = 'DisableTwoFactor';
    const CONFIRM_LOGIN = 'ConfirmLogin';
    const CONFIRM_WITHDRAW = 'ConfirmWithdraw';
    const CHECK_IS_ONLINE = 'CheckIsOnline';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ENABLE_TWO_FACTOR,
            self::CANCEL_ENABLE_TWO_FACTOR,
            self::DISABLE_TWO_FACTOR,
            self::CONFIRM_LOGIN,
            self::CONFIRM_WITHDRAW,
            self::CHECK_IS_ONLINE,
        ];
    }
}


