<?php
/**
 * OrderState
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BCFLEX API
 *
 * BCFLEX Public API Documentation
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * OrderState Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderState
{
    /**
     * Possible values of this enum
     */
    const WAITING_FOR_ACTIVATION = 'WaitingForActivation';
    const ON_MARKET = 'OnMarket';
    const PARTIALLY_FILLED = 'PartiallyFilled';
    const CANCELLED = 'Cancelled';
    const REJECTED = 'Rejected';
    const CLOSE_FILLED = 'Close_Filled';
    const CANCELLED_BY_USER = 'Cancelled_ByUser';
    const CLOSE_MARGIN_CALL = 'Close_MarginCall';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WAITING_FOR_ACTIVATION,
            self::ON_MARKET,
            self::PARTIALLY_FILLED,
            self::CANCELLED,
            self::REJECTED,
            self::CLOSE_FILLED,
            self::CANCELLED_BY_USER,
            self::CLOSE_MARGIN_CALL,
        ];
    }
}


