<?php
/**
 * Order
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BCFLEX API
 *
 * BCFLEX Public API Documentation
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Order Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class Order implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Order';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'trade_type' => '\OpenAPI\Client\Model\TradeType',
        'order_type' => '\OpenAPI\Client\Model\OrderTypes',
        'order_state' => '\OpenAPI\Client\Model\OrderState',
        'trade_pairname' => 'string',
        'amount' => 'double',
        'amount_left' => 'double',
        'price' => 'double',
        'stop_loss_price' => 'double',
        'take_profit_price' => 'double',
        'is_margin' => 'bool',
        'liquidation_price' => 'double',
        'initial_price' => 'double',
        'leverage' => 'int',
        'initial_amount' => 'double',
        'close_position_price' => 'double',
        'date_created' => 'int',
        'date_closed' => 'int',
        'date_on_market' => 'int',
        'closed' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'trade_type' => null,
        'order_type' => null,
        'order_state' => null,
        'trade_pairname' => null,
        'amount' => 'double',
        'amount_left' => 'double',
        'price' => 'double',
        'stop_loss_price' => 'double',
        'take_profit_price' => 'double',
        'is_margin' => null,
        'liquidation_price' => 'double',
        'initial_price' => 'double',
        'leverage' => 'int32',
        'initial_amount' => 'double',
        'close_position_price' => 'double',
        'date_created' => 'int64',
        'date_closed' => 'int64',
        'date_on_market' => 'int64',
        'closed' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'trade_type' => 'tradeType',
        'order_type' => 'orderType',
        'order_state' => 'orderState',
        'trade_pairname' => 'tradePairname',
        'amount' => 'amount',
        'amount_left' => 'amountLeft',
        'price' => 'price',
        'stop_loss_price' => 'stopLossPrice',
        'take_profit_price' => 'takeProfitPrice',
        'is_margin' => 'isMargin',
        'liquidation_price' => 'liquidationPrice',
        'initial_price' => 'initialPrice',
        'leverage' => 'leverage',
        'initial_amount' => 'initialAmount',
        'close_position_price' => 'closePositionPrice',
        'date_created' => 'dateCreated',
        'date_closed' => 'dateClosed',
        'date_on_market' => 'dateOnMarket',
        'closed' => 'closed'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'trade_type' => 'setTradeType',
        'order_type' => 'setOrderType',
        'order_state' => 'setOrderState',
        'trade_pairname' => 'setTradePairname',
        'amount' => 'setAmount',
        'amount_left' => 'setAmountLeft',
        'price' => 'setPrice',
        'stop_loss_price' => 'setStopLossPrice',
        'take_profit_price' => 'setTakeProfitPrice',
        'is_margin' => 'setIsMargin',
        'liquidation_price' => 'setLiquidationPrice',
        'initial_price' => 'setInitialPrice',
        'leverage' => 'setLeverage',
        'initial_amount' => 'setInitialAmount',
        'close_position_price' => 'setClosePositionPrice',
        'date_created' => 'setDateCreated',
        'date_closed' => 'setDateClosed',
        'date_on_market' => 'setDateOnMarket',
        'closed' => 'setClosed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'trade_type' => 'getTradeType',
        'order_type' => 'getOrderType',
        'order_state' => 'getOrderState',
        'trade_pairname' => 'getTradePairname',
        'amount' => 'getAmount',
        'amount_left' => 'getAmountLeft',
        'price' => 'getPrice',
        'stop_loss_price' => 'getStopLossPrice',
        'take_profit_price' => 'getTakeProfitPrice',
        'is_margin' => 'getIsMargin',
        'liquidation_price' => 'getLiquidationPrice',
        'initial_price' => 'getInitialPrice',
        'leverage' => 'getLeverage',
        'initial_amount' => 'getInitialAmount',
        'close_position_price' => 'getClosePositionPrice',
        'date_created' => 'getDateCreated',
        'date_closed' => 'getDateClosed',
        'date_on_market' => 'getDateOnMarket',
        'closed' => 'getClosed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['trade_type'] = $data['trade_type'] ?? null;
        $this->container['order_type'] = $data['order_type'] ?? null;
        $this->container['order_state'] = $data['order_state'] ?? null;
        $this->container['trade_pairname'] = $data['trade_pairname'] ?? null;
        $this->container['amount'] = $data['amount'] ?? null;
        $this->container['amount_left'] = $data['amount_left'] ?? null;
        $this->container['price'] = $data['price'] ?? null;
        $this->container['stop_loss_price'] = $data['stop_loss_price'] ?? null;
        $this->container['take_profit_price'] = $data['take_profit_price'] ?? null;
        $this->container['is_margin'] = $data['is_margin'] ?? null;
        $this->container['liquidation_price'] = $data['liquidation_price'] ?? null;
        $this->container['initial_price'] = $data['initial_price'] ?? null;
        $this->container['leverage'] = $data['leverage'] ?? null;
        $this->container['initial_amount'] = $data['initial_amount'] ?? null;
        $this->container['close_position_price'] = $data['close_position_price'] ?? null;
        $this->container['date_created'] = $data['date_created'] ?? null;
        $this->container['date_closed'] = $data['date_closed'] ?? null;
        $this->container['date_on_market'] = $data['date_on_market'] ?? null;
        $this->container['closed'] = $data['closed'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets trade_type
     *
     * @return \OpenAPI\Client\Model\TradeType|null
     */
    public function getTradeType()
    {
        return $this->container['trade_type'];
    }

    /**
     * Sets trade_type
     *
     * @param \OpenAPI\Client\Model\TradeType|null $trade_type trade_type
     *
     * @return self
     */
    public function setTradeType($trade_type)
    {
        $this->container['trade_type'] = $trade_type;

        return $this;
    }

    /**
     * Gets order_type
     *
     * @return \OpenAPI\Client\Model\OrderTypes|null
     */
    public function getOrderType()
    {
        return $this->container['order_type'];
    }

    /**
     * Sets order_type
     *
     * @param \OpenAPI\Client\Model\OrderTypes|null $order_type order_type
     *
     * @return self
     */
    public function setOrderType($order_type)
    {
        $this->container['order_type'] = $order_type;

        return $this;
    }

    /**
     * Gets order_state
     *
     * @return \OpenAPI\Client\Model\OrderState|null
     */
    public function getOrderState()
    {
        return $this->container['order_state'];
    }

    /**
     * Sets order_state
     *
     * @param \OpenAPI\Client\Model\OrderState|null $order_state order_state
     *
     * @return self
     */
    public function setOrderState($order_state)
    {
        $this->container['order_state'] = $order_state;

        return $this;
    }

    /**
     * Gets trade_pairname
     *
     * @return string|null
     */
    public function getTradePairname()
    {
        return $this->container['trade_pairname'];
    }

    /**
     * Sets trade_pairname
     *
     * @param string|null $trade_pairname trade_pairname
     *
     * @return self
     */
    public function setTradePairname($trade_pairname)
    {
        $this->container['trade_pairname'] = $trade_pairname;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return double|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param double|null $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets amount_left
     *
     * @return double|null
     */
    public function getAmountLeft()
    {
        return $this->container['amount_left'];
    }

    /**
     * Sets amount_left
     *
     * @param double|null $amount_left amount_left
     *
     * @return self
     */
    public function setAmountLeft($amount_left)
    {
        $this->container['amount_left'] = $amount_left;

        return $this;
    }

    /**
     * Gets price
     *
     * @return double|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param double|null $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets stop_loss_price
     *
     * @return double|null
     */
    public function getStopLossPrice()
    {
        return $this->container['stop_loss_price'];
    }

    /**
     * Sets stop_loss_price
     *
     * @param double|null $stop_loss_price stop_loss_price
     *
     * @return self
     */
    public function setStopLossPrice($stop_loss_price)
    {
        $this->container['stop_loss_price'] = $stop_loss_price;

        return $this;
    }

    /**
     * Gets take_profit_price
     *
     * @return double|null
     */
    public function getTakeProfitPrice()
    {
        return $this->container['take_profit_price'];
    }

    /**
     * Sets take_profit_price
     *
     * @param double|null $take_profit_price take_profit_price
     *
     * @return self
     */
    public function setTakeProfitPrice($take_profit_price)
    {
        $this->container['take_profit_price'] = $take_profit_price;

        return $this;
    }

    /**
     * Gets is_margin
     *
     * @return bool|null
     */
    public function getIsMargin()
    {
        return $this->container['is_margin'];
    }

    /**
     * Sets is_margin
     *
     * @param bool|null $is_margin is_margin
     *
     * @return self
     */
    public function setIsMargin($is_margin)
    {
        $this->container['is_margin'] = $is_margin;

        return $this;
    }

    /**
     * Gets liquidation_price
     *
     * @return double|null
     */
    public function getLiquidationPrice()
    {
        return $this->container['liquidation_price'];
    }

    /**
     * Sets liquidation_price
     *
     * @param double|null $liquidation_price liquidation_price
     *
     * @return self
     */
    public function setLiquidationPrice($liquidation_price)
    {
        $this->container['liquidation_price'] = $liquidation_price;

        return $this;
    }

    /**
     * Gets initial_price
     *
     * @return double|null
     */
    public function getInitialPrice()
    {
        return $this->container['initial_price'];
    }

    /**
     * Sets initial_price
     *
     * @param double|null $initial_price initial_price
     *
     * @return self
     */
    public function setInitialPrice($initial_price)
    {
        $this->container['initial_price'] = $initial_price;

        return $this;
    }

    /**
     * Gets leverage
     *
     * @return int|null
     */
    public function getLeverage()
    {
        return $this->container['leverage'];
    }

    /**
     * Sets leverage
     *
     * @param int|null $leverage leverage
     *
     * @return self
     */
    public function setLeverage($leverage)
    {
        $this->container['leverage'] = $leverage;

        return $this;
    }

    /**
     * Gets initial_amount
     *
     * @return double|null
     */
    public function getInitialAmount()
    {
        return $this->container['initial_amount'];
    }

    /**
     * Sets initial_amount
     *
     * @param double|null $initial_amount initial_amount
     *
     * @return self
     */
    public function setInitialAmount($initial_amount)
    {
        $this->container['initial_amount'] = $initial_amount;

        return $this;
    }

    /**
     * Gets close_position_price
     *
     * @return double|null
     */
    public function getClosePositionPrice()
    {
        return $this->container['close_position_price'];
    }

    /**
     * Sets close_position_price
     *
     * @param double|null $close_position_price close_position_price
     *
     * @return self
     */
    public function setClosePositionPrice($close_position_price)
    {
        $this->container['close_position_price'] = $close_position_price;

        return $this;
    }

    /**
     * Gets date_created
     *
     * @return int|null
     */
    public function getDateCreated()
    {
        return $this->container['date_created'];
    }

    /**
     * Sets date_created
     *
     * @param int|null $date_created date_created
     *
     * @return self
     */
    public function setDateCreated($date_created)
    {
        $this->container['date_created'] = $date_created;

        return $this;
    }

    /**
     * Gets date_closed
     *
     * @return int|null
     */
    public function getDateClosed()
    {
        return $this->container['date_closed'];
    }

    /**
     * Sets date_closed
     *
     * @param int|null $date_closed date_closed
     *
     * @return self
     */
    public function setDateClosed($date_closed)
    {
        $this->container['date_closed'] = $date_closed;

        return $this;
    }

    /**
     * Gets date_on_market
     *
     * @return int|null
     */
    public function getDateOnMarket()
    {
        return $this->container['date_on_market'];
    }

    /**
     * Sets date_on_market
     *
     * @param int|null $date_on_market date_on_market
     *
     * @return self
     */
    public function setDateOnMarket($date_on_market)
    {
        $this->container['date_on_market'] = $date_on_market;

        return $this;
    }

    /**
     * Gets closed
     *
     * @return bool|null
     */
    public function getClosed()
    {
        return $this->container['closed'];
    }

    /**
     * Sets closed
     *
     * @param bool|null $closed closed
     *
     * @return self
     */
    public function setClosed($closed)
    {
        $this->container['closed'] = $closed;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


