<?php
/**
 * Type
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BCFLEX API
 *
 * BCFLEX Public API Documentation
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Type Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Type
{
    /**
     * Possible values of this enum
     */
    const BTC_BASED = 'BtcBased';
    const ETH_BASED = 'EthBased';
    const FIAT = 'Fiat';
    const RIPPLE = 'Ripple';
    const EOS = 'Eos';
    const ERC20 = 'ERC20';
    const TRON = 'Tron';
    const TRC20 = 'TRC20';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BTC_BASED,
            self::ETH_BASED,
            self::FIAT,
            self::RIPPLE,
            self::EOS,
            self::ERC20,
            self::TRON,
            self::TRC20,
        ];
    }
}


