<?php
/**
 * UserAdminCommand
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BCFLEX API
 *
 * BCFLEX Public API Documentation
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * UserAdminCommand Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserAdminCommand
{
    /**
     * Possible values of this enum
     */
    const BLOCK_USER = 'BlockUser';
    const UNBLOCK_USER = 'UnblockUser';
    const VERIFY_EMAIL = 'VerifyEmail';
    const TWO_FACTOR_DISABLE = 'TwoFactorDisable';
    const RESET_PASSWORD = 'ResetPassword';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BLOCK_USER,
            self::UNBLOCK_USER,
            self::VERIFY_EMAIL,
            self::TWO_FACTOR_DISABLE,
            self::RESET_PASSWORD,
        ];
    }
}


