<?php
/**
 * AdminApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BCFLEX API
 *
 * BCFLEX Public API Documentation
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdminApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdminApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiAdminAddcointokenPost
     *
     * .
     *
     */
    public function testApiAdminAddcointokenPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiAdminGetuserdataPost
     *
     * .
     *
     */
    public function testApiAdminGetuserdataPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiAdminGetusertradedataPost
     *
     * .
     *
     */
    public function testApiAdminGetusertradedataPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiAdminSearchuserGet
     *
     * .
     *
     */
    public function testApiAdminSearchuserGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiAdminUsercommandPost
     *
     * .
     *
     */
    public function testApiAdminUsercommandPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionAdminAddcointokenPost
     *
     * .
     *
     */
    public function testApiVversionAdminAddcointokenPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionAdminGetuserdataPost
     *
     * .
     *
     */
    public function testApiVversionAdminGetuserdataPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionAdminGetusertradedataPost
     *
     * .
     *
     */
    public function testApiVversionAdminGetusertradedataPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionAdminSearchuserGet
     *
     * .
     *
     */
    public function testApiVversionAdminSearchuserGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionAdminUsercommandPost
     *
     * .
     *
     */
    public function testApiVversionAdminUsercommandPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
