<?php
/**
 * ApplicationApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BCFLEX API
 *
 * BCFLEX Public API Documentation
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ApplicationApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApplicationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiApplicationDisableGoogle2stepPost
     *
     * .
     *
     */
    public function testApiApplicationDisableGoogle2stepPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationEnableGoogle2stepPost
     *
     * .
     *
     */
    public function testApiApplicationEnableGoogle2stepPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationPackagePost
     *
     * .
     *
     */
    public function testApiApplicationPackagePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationProcessFaceImagePost
     *
     * .
     *
     */
    public function testApiApplicationProcessFaceImagePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationProcessPassportImagePost
     *
     * .
     *
     */
    public function testApiApplicationProcessPassportImagePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationPublicKeyPut
     *
     * .
     *
     */
    public function testApiApplicationPublicKeyPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationRatesGet
     *
     * .
     *
     */
    public function testApiApplicationRatesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationRestorePinPost
     *
     * .
     *
     */
    public function testApiApplicationRestorePinPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationSetpinPut
     *
     * .
     *
     */
    public function testApiApplicationSetpinPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationSetpushtokenPost
     *
     * .
     *
     */
    public function testApiApplicationSetpushtokenPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationTestGet
     *
     * .
     *
     */
    public function testApiApplicationTestGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationValidatePinPost
     *
     * .
     *
     */
    public function testApiApplicationValidatePinPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiApplicationVerifyfacesPost
     *
     * .
     *
     */
    public function testApiApplicationVerifyfacesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationDisableGoogle2stepPost
     *
     * .
     *
     */
    public function testApiVversionApplicationDisableGoogle2stepPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationEnableGoogle2stepPost
     *
     * .
     *
     */
    public function testApiVversionApplicationEnableGoogle2stepPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationPackagePost
     *
     * .
     *
     */
    public function testApiVversionApplicationPackagePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationProcessFaceImagePost
     *
     * .
     *
     */
    public function testApiVversionApplicationProcessFaceImagePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationProcessPassportImagePost
     *
     * .
     *
     */
    public function testApiVversionApplicationProcessPassportImagePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationPublicKeyPut
     *
     * .
     *
     */
    public function testApiVversionApplicationPublicKeyPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationRatesGet
     *
     * .
     *
     */
    public function testApiVversionApplicationRatesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationRestorePinPost
     *
     * .
     *
     */
    public function testApiVversionApplicationRestorePinPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationSetpinPut
     *
     * .
     *
     */
    public function testApiVversionApplicationSetpinPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationSetpushtokenPost
     *
     * .
     *
     */
    public function testApiVversionApplicationSetpushtokenPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationTestGet
     *
     * .
     *
     */
    public function testApiVversionApplicationTestGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationValidatePinPost
     *
     * .
     *
     */
    public function testApiVversionApplicationValidatePinPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionApplicationVerifyfacesPost
     *
     * .
     *
     */
    public function testApiVversionApplicationVerifyfacesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
