<?php
/**
 * GuardApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BCFLEX API
 *
 * BCFLEX Public API Documentation
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GuardApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GuardApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiGuardGetAccessTokensGet
     *
     * .
     *
     */
    public function testApiGuardGetAccessTokensGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiGuardGetlastGet
     *
     * .
     *
     */
    public function testApiGuardGetlastGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiGuardPrecheckLogoutPost
     *
     * .
     *
     */
    public function testApiGuardPrecheckLogoutPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiGuardRequestGet
     *
     * .
     *
     */
    public function testApiGuardRequestGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiGuardRequestPost
     *
     * .
     *
     */
    public function testApiGuardRequestPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiGuardRequestSettingsTokenPost
     *
     * .
     *
     */
    public function testApiGuardRequestSettingsTokenPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiGuardRevokeTokenByIdPost
     *
     * .
     *
     */
    public function testApiGuardRevokeTokenByIdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiGuardRevokeTokenPost
     *
     * .
     *
     */
    public function testApiGuardRevokeTokenPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiGuardSubmitPost
     *
     * .
     *
     */
    public function testApiGuardSubmitPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiGuardUpdatePost
     *
     * .
     *
     */
    public function testApiGuardUpdatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionGuardGetAccessTokensGet
     *
     * .
     *
     */
    public function testApiVversionGuardGetAccessTokensGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionGuardGetlastGet
     *
     * .
     *
     */
    public function testApiVversionGuardGetlastGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionGuardPrecheckLogoutPost
     *
     * .
     *
     */
    public function testApiVversionGuardPrecheckLogoutPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionGuardRequestGet
     *
     * .
     *
     */
    public function testApiVversionGuardRequestGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionGuardRequestPost
     *
     * .
     *
     */
    public function testApiVversionGuardRequestPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionGuardRequestSettingsTokenPost
     *
     * .
     *
     */
    public function testApiVversionGuardRequestSettingsTokenPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionGuardRevokeTokenByIdPost
     *
     * .
     *
     */
    public function testApiVversionGuardRevokeTokenByIdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionGuardRevokeTokenPost
     *
     * .
     *
     */
    public function testApiVversionGuardRevokeTokenPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionGuardSubmitPost
     *
     * .
     *
     */
    public function testApiVversionGuardSubmitPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiVversionGuardUpdatePost
     *
     * .
     *
     */
    public function testApiVversionGuardUpdatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
